[package]
name = "poc"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.11.1", features = ["boolean", "shortint", "integer"] }
bincode = "1.3.3"

[[bin]]
name = "keys"
path = "src/keys.rs"